### ISSUE TITLE
Multiplas notificações

### ISSUE THREAD

**Issue by abritolda** [gabrieldeoliveira96/BiometriaFMX#1]
No android, quando executas varias vezes o seguinte codigo
"  Android:= TEventResultClass.Create(self);
  if Android.DeviceSecure then
    Android.StartActivityKeyGuard; "
recebe o numero notificações dos pedidos anterior. Se executou 3 vezes vai receber 3 vezes a notificação "valido" se executou 4 vezes vai receber 4 vezes valido. Isto porque a variavel "Android" nunca é destruida.

Passando a variavel Android para public e de seguida
Se alterar na unit Android.keyguardmanager. pas o seguinte procedimento

procedure TEventResultClass.OnActivityResult(Sender: TObject; const ARequestCode, AResultCode: Integer;
  const AIntent: TIntent);
begin
  if aRequestCode = 000 then
  begin
    if AResultCode = -1 then
    begin
      ShowMessage('Valido');
      Form1.TabControl1.ActiveTab:= Form1.TabItemPrincipal;
      Form1.Android.DisposeOf;  // aqui é destruido  a variavel e assim ja so recebe uma notificação por pedido
    end
    else
    begin
      ShowMessage('Inválido');
    end;
  end;

end;

Ps: Não me parece ser a melhor maneir de o fazer. No entanto resulta

**Comment by gabrieldeoliveira96** [comment]
Boa tarde tudo certo ?,
O Código disponibilizado é apenas um exemplo básico,
O código monstra as possibilidades, a partir dai, cada desenvolvedor deve fazer a sua própria solução ...
Agradeço o feedback, porem isso eu já sabia,
Criei o código desse jeito para ser mais didático na palestra...


Agradeço o Feedback, e fique a vontade para entrar em contato.



Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: abritolda<mailto:notifications@github.com>
Enviado:segunda-feira, 17 de fevereiro de 2020 15:30
Para: gabrieldeoliveira96/BiometriaFMX<mailto:BiometriaFMX@noreply.github.com>
Cc:Subscribed<mailto:subscribed@noreply.github.com>
Assunto: [gabrieldeoliveira96/BiometriaFMX] Multiplas notificações (#1)


No android, quando executas varias vezes o seguinte codigo
" Android:= TEventResultClass.Create(self);
if Android.DeviceSecure then
Android.StartActivityKeyGuard; "
recebe o numero notificações dos pedidos anterior. Se executou 3 vezes vai receber 3 vezes a notificação "valido" se executou 4 vezes vai receber 4 vezes valido. Isto porque a variavel "Android" nunca é destruida.

Passando a variavel Android para public e de seguida
Se alterar na unit Android.keyguardmanager. pas o seguinte procedimento

procedure TEventResultClass.OnActivityResult(Sender: TObject; const ARequestCode, AResultCode: Integer;
const AIntent: TIntent);
begin
if aRequestCode = 000 then
begin
if AResultCode = -1 then
begin
ShowMessage('Valido');
Form1.TabControl1.ActiveTab:= Form1.TabItemPrincipal;
Form1.Android.DisposeOf; // aqui é destruido a variavel e assim ja so recebe uma notificação por pedido
end
else
begin
ShowMessage('Inválido');
end;
end;

end;

Ps: Não me parece ser a melhor maneir de o fazer. No entanto resulta

**Comment by abritolda** [comment]
Bravo, Belo trabalho e excelente partilha de código.

**Comment by gabrieldeoliveira96** [comment]
Eu que agradeço ter assistido a palestra e ter gostado da solução amigo,
Sempre que precisar estou a disposição!!.
Agraços!!
Bora Codar.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: abritolda<mailto:notifications@github.com>
Enviado:segunda-feira, 17 de fevereiro de 2020 15:42
Para: gabrieldeoliveira96/BiometriaFMX<mailto:BiometriaFMX@noreply.github.com>
Cc:gabrieldeoliveira96<mailto:gabriel.o.s@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Assunto: Re: [gabrieldeoliveira96/BiometriaFMX] Multiplas notificações (#1)


Bravo, Belo trabalho e excelente partilha de código.
